name: C++ Build on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MSVC environment and compile
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath > installationPath.txt
          set /p installationPath=<installationPath.txt
          cmd.exe /c "%installationPath%\VC\Auxiliary\Build\vcvars64.bat && cl /EHsc chrome_decrypt.cpp ole32.lib oleaut32.lib shell32.lib version.lib comsuppw.lib advapi32.lib shlwapi.lib /link /out:chrome_decrypt.exe"
          
      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: chrome_decrypt.exe
          path: chrome_decrypt.exe
