name: Build C++ Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Configuration type to build.
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[17.0,)'

    - name: Build with cl
      run: cl /EHsc chrome_decrypt.cpp oleaut32.lib shell32.lib advapi32.lib shlwapi.lib

    - name: Copy executable to Chrome directory
      run: |
        Copy-Item -Path "chrome_decrypt.exe" -Destination "C:\Program Files\Google\Chrome\Application"

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: chrome_decrypt
        path: C:\Program Files\Google\Chrome\Application\chrome_decrypt.exe
