name: Build C++ Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Configuration type to build.
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[17.0,)'
        msbuild-architecture: x64

    - name: Build with Visual Studio
      run: |
        cmd /c "\"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat\" && cl /EHsc chrome_decrypt.cpp oleaut32.lib shell32.lib advapi32.lib shlwapi.lib /link /out:chrome_decrypt.exe"

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: chrome_decrypt
        path: chrome_decrypt.exe
